spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/multiple-datesource?characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&allowMultiQueries=true&serverTimezone=UTC
        read-only: false
        username: root
        password:

    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/multiple-datesource?serverTimezone=UTC
        read-only: true
        username: root
        password:

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.auto: none
        format_sql: true

# For Debug
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE