spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/multiple-datesource?characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
